name: sync rss with notion databases

on:
  schedule:
    - cron: 0 17 * * * # JST 0:00
  # 再実行やデバッグ用に手動でも実行可能にしておく
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn sync
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          FEED_SOURSES_NOTION_DATABASE_ID: ${{ secrets.FEED_SOURSES_NOTION_DATABASE_ID }}
          ARTICLES_NOTION_DATABASE_ID: ${{ secrets.ARTICLES_NOTION_DATABASE_ID }}
